
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

mqtt:
  sensor:
    - name: "Example Temperature"
      state_topic: "home-assistant/example-sensor/sensor"
      unit_of_measurement: "°C"
      value_template: "{{ value_json.temperature }}"
    - name: "Example Humidity"
      state_topic: "home-assistant/example-sensor/sensor"
      unit_of_measurement: "%"
      value_template: "{{ value_json.humidity }}"

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
